// Fluid V5 M4.3 split-sum GGX IBL.
// Builds a GGX-prefiltered specular cube, a cosine-weighted diffuse irradiance cube and a BRDF
// integration LUT from the active true-HDR environment. The precompute runs only when env.gen
// changes; per-frame shading is a small derivative-free water-only pass.

const ssfr=window.__ssfr,dev=ssfr?.dev,state=window.__v5State;
if(!dev||!ssfr?.format)throw new Error('Fluid V5 M4.3 IBL: runtime unavailable.');
const format=ssfr.format,q=new URLSearchParams(location.search),quality=['low','medium','high'].includes(q.get('quality'))?q.get('quality'):'medium';
const isIOS=/iPad|iPhone|iPod/i.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
const PREF_SIZE=isIOS?(quality==='low'?64:128):(quality==='high'?256:128),IRR_SIZE=32,BRDF_SIZE=isIOS?96:128,SAMPLES=isIOS?16:24;
const MIPS=Math.floor(Math.log2(PREF_SIZE))+1;
window.__v5IBLStatus={online:false,stage:'precompute',backend:'split-sum-ggx-m43',error:'',prefilter:PREF_SIZE,irradiance:IRR_SIZE,brdf:BRDF_SIZE};

const fullVS=`struct V{@builtin(position)p:vec4f,@location(0)uv:vec2f}@vertex fn vs(@builtin(vertex_index)i:u32)->V{let q=vec2f(f32((i<<1u)&2u),f32(i&2u));var o:V;o.uv=q;o.p=vec4f(q*2.0-1.0,0,1);return o;}`;
const shared=`
const PI=3.14159265359;
fn reverseBits(v0:u32)->u32{var v=v0;v=((v<<16u)|(v>>16u));v=((v&0x00ff00ffu)<<8u)|((v&0xff00ff00u)>>8u);v=((v&0x0f0f0f0fu)<<4u)|((v&0xf0f0f0f0u)>>4u);v=((v&0x33333333u)<<2u)|((v&0xccccccccu)>>2u);v=((v&0x55555555u)<<1u)|((v&0xaaaaaaaau)>>1u);return v;}
fn hammersley(i:u32,n:u32)->vec2f{return vec2f(f32(i)/max(f32(n),1.0),f32(reverseBits(i))*2.3283064365386963e-10);}
fn basis(n:vec3f)->mat3x3f{let up=select(vec3f(0,0,1),vec3f(1,0,0),abs(n.z)>.999);let t=normalize(cross(up,n));let b=cross(n,t);return mat3x3f(t,b,n);}
fn faceDir(face:u32,uv:vec2f)->vec3f{let s=uv.x*2.0-1.0;let t=uv.y*2.0-1.0;var d=vec3f(0);switch face{case 0u:{d=vec3f(1,-t,-s);}case 1u:{d=vec3f(-1,-t,s);}case 2u:{d=vec3f(s,1,t);}case 3u:{d=vec3f(s,-1,-t);}case 4u:{d=vec3f(s,-t,1);}default:{d=vec3f(-s,-t,-1);}}return normalize(d);}
`;
const prefilterWGSL=fullVS+shared+`
struct P{face:u32,rough:f32,sourceLod:f32,samples:u32}@group(0)@binding(0)var<uniform>U:P;@group(0)@binding(1)var src:texture_cube<f32>;@group(0)@binding(2)var samp:sampler;
fn importance(xi:vec2f,n:vec3f,r:f32)->vec3f{let a=max(r*r,.002);let a2=a*a;let phi=2.0*PI*xi.x;let cosT=sqrt((1.0-xi.y)/(1.0+(a2-1.0)*xi.y));let sinT=sqrt(max(0.0,1.0-cosT*cosT));let h=basis(n)*vec3f(cos(phi)*sinT,sin(phi)*sinT,cosT);return normalize(h);}
@fragment fn fs(v:V)->@location(0)vec4f{let n=faceDir(U.face,v.uv);if(U.rough<.015){return vec4f(textureSampleLevel(src,samp,n,0).rgb,1);}let vv=n;var sum=vec3f(0);var w=0.0;for(var i=0u;i<32u;i++){if(i>=U.samples){break;}let h=importance(hammersley(i,U.samples),n,U.rough);let l=normalize(2.0*dot(vv,h)*h-vv);let nl=max(dot(n,l),0.0);if(nl>0){sum+=textureSampleLevel(src,samp,l,U.sourceLod).rgb*nl;w+=nl;}}return vec4f(sum/max(w,1e-4),1);}`;
const irradianceWGSL=fullVS+shared+`
struct P{face:u32,p0:f32,p1:f32,samples:u32}@group(0)@binding(0)var<uniform>U:P;@group(0)@binding(1)var src:texture_cube<f32>;@group(0)@binding(2)var samp:sampler;
@fragment fn fs(v:V)->@location(0)vec4f{let n=faceDir(U.face,v.uv);let B=basis(n);var sum=vec3f(0);for(var i=0u;i<32u;i++){if(i>=U.samples){break;}let xi=hammersley(i,U.samples);let phi=2.0*PI*xi.x;let r=sqrt(xi.y);let z=sqrt(max(0.0,1.0-xi.y));let l=normalize(B*vec3f(cos(phi)*r,sin(phi)*r,z));sum+=textureSampleLevel(src,samp,l,4.0).rgb;}return vec4f(sum/max(f32(U.samples),1.0),1);}`;
const brdfWGSL=fullVS+shared+`
fn importance(xi:vec2f,n:vec3f,r:f32)->vec3f{let a=max(r*r,.002);let a2=a*a;let phi=2.0*PI*xi.x;let cosT=sqrt((1.0-xi.y)/(1.0+(a2-1.0)*xi.y));let sinT=sqrt(max(0.0,1.0-cosT*cosT));return normalize(basis(n)*vec3f(cos(phi)*sinT,sin(phi)*sinT,cosT));}
fn G1(nv:f32,r:f32)->f32{let k=(r*r)*.5;return nv/max(nv*(1.0-k)+k,1e-4);}
@fragment fn fs(v:V)->@location(0)vec4f{let nv=clamp(v.uv.x,.001,.999),r=clamp(v.uv.y,.002,.999);let n=vec3f(0,0,1);let vv=vec3f(sqrt(max(0.0,1.0-nv*nv)),0,nv);var A=0.0;var Bv=0.0;for(var i=0u;i<64u;i++){let h=importance(hammersley(i,64u),n,r);let l=normalize(2.0*dot(vv,h)*h-vv);let nl=max(l.z,0.0),nh=max(h.z,0.0),vh=max(dot(vv,h),0.0);if(nl>0){let G=G1(nv,r)*G1(nl,r);let vis=(G*vh)/max(nh*nv,1e-4);let Fc=pow(1.0-vh,5.0);A+=(1.0-Fc)*vis;Bv+=Fc*vis;}}return vec4f(A/64.0,Bv/64.0,0,1);}`;
const preMod=dev.createShaderModule({code:prefilterWGSL,label:'fluidV5M43PrefilterWGSL'}),irrMod=dev.createShaderModule({code:irradianceWGSL,label:'fluidV5M43IrradianceWGSL'}),brdfMod=dev.createShaderModule({code:brdfWGSL,label:'fluidV5M43BRDFWGSL'});
const prePipe=await dev.createRenderPipelineAsync({label:'fluidV5M43Prefilter',layout:'auto',vertex:{module:preMod,entryPoint:'vs'},fragment:{module:preMod,entryPoint:'fs',targets:[{format:'rgba16float'}]},primitive:{topology:'triangle-list'}});
const irrPipe=await dev.createRenderPipelineAsync({label:'fluidV5M43Irradiance',layout:'auto',vertex:{module:irrMod,entryPoint:'vs'},fragment:{module:irrMod,entryPoint:'fs',targets:[{format:'rgba16float'}]},primitive:{topology:'triangle-list'}});
const brdfPipe=await dev.createRenderPipelineAsync({label:'fluidV5M43BRDF',layout:'auto',vertex:{module:brdfMod,entryPoint:'vs'},fragment:{module:brdfMod,entryPoint:'fs',targets:[{format:'rgba16float'}]},primitive:{topology:'triangle-list'}});
const linear=dev.createSampler({magFilter:'linear',minFilter:'linear',mipmapFilter:'linear',addressModeU:'clamp-to-edge',addressModeV:'clamp-to-edge'});
let prefTex=null,prefView=null,irrTex=null,irrView=null,brdfTex=null,brdfView=null,preGen=-1,brdfReady=false,shadeBind=null,shadeKey='';
function makeU(face,rough=0,lod=0,samples=SAMPLES){const b=dev.createBuffer({size:16,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});const a=new ArrayBuffer(16),u=new Uint32Array(a),f=new Float32Array(a);u[0]=face;f[1]=rough;f[2]=lod;u[3]=samples;dev.queue.writeBuffer(b,0,a);return b;}
function ensureTextures(){if(prefTex)return;prefTex=dev.createTexture({label:'fluidV5M43GGXPrefilter',size:[PREF_SIZE,PREF_SIZE,6],format:'rgba16float',mipLevelCount:MIPS,usage:GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.TEXTURE_BINDING});prefView=prefTex.createView({dimension:'cube'});irrTex=dev.createTexture({label:'fluidV5M43Irradiance',size:[IRR_SIZE,IRR_SIZE,6],format:'rgba16float',usage:GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.TEXTURE_BINDING});irrView=irrTex.createView({dimension:'cube'});brdfTex=dev.createTexture({label:'fluidV5M43BRDF',size:[BRDF_SIZE,BRDF_SIZE],format:'rgba16float',usage:GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.TEXTURE_BINDING});brdfView=brdfTex.createView();}
function encodePrecompute(enc){ensureTextures();if(!brdfReady){const p=enc.beginRenderPass({colorAttachments:[{view:brdfView,clearValue:{r:0,g:0,b:0,a:1},loadOp:'clear',storeOp:'store'}]});p.setPipeline(brdfPipe);p.draw(3);p.end();brdfReady=true;}
 for(let m=0;m<MIPS;m++){const rough=m/Math.max(1,MIPS-1),lod=rough*4.0;for(let face=0;face<6;face++){const u=makeU(face,rough,lod,SAMPLES),bg=dev.createBindGroup({layout:prePipe.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:u}},{binding:1,resource:ssfr.env.view},{binding:2,resource:ssfr.env.sampler}]});const view=prefTex.createView({dimension:'2d',baseMipLevel:m,mipLevelCount:1,baseArrayLayer:face,arrayLayerCount:1});const p=enc.beginRenderPass({colorAttachments:[{view,clearValue:{r:0,g:0,b:0,a:1},loadOp:'clear',storeOp:'store'}]});p.setPipeline(prePipe);p.setBindGroup(0,bg);p.draw(3);p.end();}}
 for(let face=0;face<6;face++){const u=makeU(face,0,0,SAMPLES),bg=dev.createBindGroup({layout:irrPipe.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:u}},{binding:1,resource:ssfr.env.view},{binding:2,resource:ssfr.env.sampler}]});const view=irrTex.createView({dimension:'2d',baseArrayLayer:face,arrayLayerCount:1});const p=enc.beginRenderPass({colorAttachments:[{view,clearValue:{r:0,g:0,b:0,a:1},loadOp:'clear',storeOp:'store'}]});p.setPipeline(irrPipe);p.setBindGroup(0,bg);p.draw(3);p.end();}
 preGen=ssfr.env.gen||0;shadeBind=null;window.__v5IBLStatus={online:true,stage:'online',backend:'split-sum-ggx-m43',error:'',prefilter:PREF_SIZE,irradiance:IRR_SIZE,brdf:BRDF_SIZE,samples:SAMPLES};}

const shadeWGSL=`
struct Comp{invViewProj:mat4x4f,invView:mat4x4f,eye:vec4f,boxMin:vec3f,proj00:f32,boxMax:vec3f,proj11:f32,absorb:vec3f,ior:f32,sunDir:vec3f,sunIntensity:f32,roughness:f32,exposure:f32,groundReflection:f32,thicknessScale:f32,bodyCount:i32,floorPlane:i32,debug:i32,hasEnvMap:i32,envIntensity:f32,envYaw:f32,mapScale:vec2f}
@group(0)@binding(0)var<uniform>C:Comp;@group(0)@binding(1)var eyeZ:texture_2d<f32>;@group(0)@binding(2)var pref:texture_cube<f32>;@group(0)@binding(3)var irr:texture_cube<f32>;@group(0)@binding(4)var brdf:texture_2d<f32>;@group(0)@binding(5)var samp:sampler;
struct V{@builtin(position)p:vec4f,@location(0)n:vec2f}@vertex fn vs(@builtin(vertex_index)i:u32)->V{let q=vec2f(f32((i<<1u)&2u),f32(i&2u))*2.0-1.0;var o:V;o.p=vec4f(q,0,1);o.n=q;return o;}fn empty(z:f32)->bool{return z < -1e3;}fn vp(ndc:vec2f,z:f32)->vec3f{return vec3f(-ndc.x*z/C.proj00,-ndc.y*z/C.proj11,z);}fn envDir(d:vec3f)->vec3f{let c=cos(C.envYaw);let s=sin(C.envYaw);return vec3f(c*d.x+s*d.z,d.y,-s*d.x+c*d.z);}
@fragment fn fs(v:V)->@location(0)vec4f{let dim=vec2i(textureDimensions(eyeZ,0)),uv=vec2f(v.n.x*.5+.5,.5-v.n.y*.5),p=vec2i(clamp(uv*vec2f(dim),vec2f(1),vec2f(dim)-vec2f(2)));let z=textureLoad(eyeZ,p,0).r;if(empty(z)){return vec4f(0);}let zx0=textureLoad(eyeZ,p+vec2i(-1,0),0).r,zx1=textureLoad(eyeZ,p+vec2i(1,0),0).r,zy0=textureLoad(eyeZ,p+vec2i(0,-1),0).r,zy1=textureLoad(eyeZ,p+vec2i(0,1),0).r;if(empty(zx0)||empty(zx1)||empty(zy0)||empty(zy1)){return vec4f(0);}let dx=vec2f(2.0/f32(dim.x),0),dy=vec2f(0,-2.0/f32(dim.y));let pc=vp(v.n,z),vx=vp(v.n+dx,zx1)-vp(v.n-dx,zx0),vy=vp(v.n+dy,zy1)-vp(v.n-dy,zy0);var nv=normalize(cross(vx,vy));if(nv.z<0){nv=-nv;}var n=normalize((C.invView*vec4f(nv,0)).xyz);let pw=(C.invView*vec4f(pc,1)).xyz;let vd=normalize(pw-C.eye.xyz);if(dot(n,-vd)<0){n=-n;}let R=reflect(vd,n),nvw=clamp(dot(n,-vd),.001,.999),rough=clamp(C.roughness,.002,.999),lod=rough*${(MIPS-1).toFixed(1)};let pre=textureSampleLevel(pref,samp,envDir(R),lod).rgb*C.envIntensity;let dfg=textureSampleLevel(brdf,samp,vec2f(nvw,rough),0).rg;let F0=vec3f(.0204);let spec=pre*(F0*dfg.x+vec3f(dfg.y));let dif=textureSampleLevel(irr,samp,envDir(n),0).rgb*C.envIntensity*vec3f(.025,.075,.095);let hdr=spec*.34+dif*.055;let mapped=pow(hdr/(vec3f(1)+hdr),vec3f(1.0/2.2));return vec4f(mapped*.34,0);}
`;
const shMod=dev.createShaderModule({code:shadeWGSL,label:'fluidV5M43ShadeWGSL'}),shadePipe=await dev.createRenderPipelineAsync({label:'fluidV5M43Shade',layout:'auto',vertex:{module:shMod,entryPoint:'vs'},fragment:{module:shMod,entryPoint:'fs',targets:[{format,blend:{color:{srcFactor:'one',dstFactor:'one'},alpha:{srcFactor:'zero',dstFactor:'one'}}}]},primitive:{topology:'triangle-list'}});
function depthSlot(){const it=Math.max(ssfr.filterIterations,0);let s=(it*2)&1;if(ssfr.cleanupPass&&it>0)s=1-s;return s;}
const baseRender=ssfr.render;ssfr.render=function(...args){const enc=args[0],target=args[1],mode=window.__v5LightState?.timeOfDay||'day';if(mode!=='night'&&this.env?.has&&window.__v5EnvironmentStatus?.online&&(this.env.gen||0)!==preGen){encodePrecompute(enc);}const out=baseRender.apply(this,args);if(mode==='night'||preGen!==(this.env?.gen||0)||!prefView||window.__v5DebugMode!=='final')return out;const slot=depthSlot(),k=`${this.gen}|${slot}|${preGen}`;if(!shadeBind||shadeKey!==k){shadeKey=k;shadeBind=dev.createBindGroup({layout:shadePipe.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this.compUni}},{binding:1,resource:this.views.eyeZ[slot]},{binding:2,resource:prefView},{binding:3,resource:irrView},{binding:4,resource:brdfView},{binding:5,resource:linear}]});}const p=enc.beginRenderPass({colorAttachments:[{view:target,loadOp:'load',storeOp:'store'}]});p.setPipeline(shadePipe);p.setBindGroup(0,shadeBind);p.draw(3);p.end();return out;};
window.__v5IBLM43={online:true,backend:'split-sum-ggx-m43',prefilter:PREF_SIZE,irradiance:IRR_SIZE,brdf:BRDF_SIZE,samples:SAMPLES};console.info(`[Fluid V5 M4.3] split-sum GGX IBL ready (${PREF_SIZE}px prefilter, ${IRR_SIZE}px irradiance, ${BRDF_SIZE}px BRDF LUT).`);
