// Fluid V5 M6.1 integrated controls/status. Appends to the already-mounted tab shell.
const state=window.__v5State;if(!state)throw new Error('Fluid V5 M6.1 UI: state unavailable.');
// M6.1 loads after the Houdini-style M6 body renderer and adds the explicit time-phased inlet
// buffer. Keeping it here means the visual renderer can fail independently while the PBF source
// and buffer diagnostics remain visible.
try{await import('./v5-waterfall-buffer-m61.js');}
catch(err){window.__v5WaterfallBufferM61={online:false,error:String(err?.message||err)};console.error('[Fluid V5 M6.1] deterministic waterfall inlet buffer rejected.',err);}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));for(let i=0;i<40&&!document.querySelector('[data-panel="physics"]');i++)await sleep(50);
const physics=document.querySelector('[data-panel="physics"]'),realism=document.querySelector('[data-panel="realism"]'),dev=document.querySelector('[data-panel="developer"]');
const save=()=>{try{localStorage.setItem('fluidV5LabStateV1',JSON.stringify(state))}catch{}};
function section(host,id,title,desc){if(!host||document.getElementById(id))return null;let d=document.createElement('div');d.id=id;d.style.cssText='margin-top:10px;padding:9px;border:1px solid rgba(78,214,220,.18);border-radius:10px;background:rgba(4,17,24,.58)';d.innerHTML=`<div style="font:800 9px ui-monospace;color:#9dffc8;letter-spacing:.10em">${title}</div><div style="font:7.4px/1.45 ui-monospace;color:#86a8b5;margin-top:5px">${desc}</div>`;host.appendChild(d);return d;}
function slider(host,label,key,min,max,step,fmt=v=>Number(v).toFixed(2)){if(!host)return;let row=document.createElement('div');row.className='v5Slider';row.innerHTML=`<label>${label}</label><input type="range" min="${min}" max="${max}" step="${step}"><div class="v5Val"></div>`;let input=row.querySelector('input'),val=row.querySelector('.v5Val');input.value=state[key];let sync=()=>val.textContent=fmt(state[key]);sync();input.oninput=e=>{e.stopPropagation();state[key]=Number(input.value);save();sync()};host.appendChild(row);}
let p=section(physics,'v5M5Physics','M5 SOLVER REFINEMENT','XPBD-style compliant density refinement runs after the base PBF solve. Shape-aware hydrodynamics samples the same GPU neighbor grid on both fluid and rigid particles, creating differential forces that become torque through the existing rigid shape matcher.');
slider(p,'XPBD DENSITY','xpbdDensity',0,1,.05);slider(p,'SHAPE HYDRO','shapeHydro',0,1.25,.05);
let r=section(realism,'v5M5Detail','M6.1 ADAPTIVE DETAIL','High-speed/high-curvature surface particles receive render-only refractive detail proxies. Sparse airborne PBF splash parcels use microdroplet surfacing, while the waterfall uses the Houdini-style reconstructed body plus a deterministic inlet buffer.');
slider(r,'SURFACE DETAIL','surfaceDetail',0,1.25,.05);
let d=section(dev,'v5M5Status','M6.1 BACKENDS','Waiting for subsystem status…');
function tick(){if(!d)return;let x=window.__v5XPBDM50,h=window.__v5RigidHydroM51,a=window.__v5AdaptiveDetailM52,v=window.__v5VolumeLightM53,w=window.__v5WhitewaterM54||window.__v5WhitewaterM41,rain=window.__v5WeatherM56,rp=window.__v5RippleM57,wf=window.__v5WaterfallM57,m60=window.__v5WaterfallM60,b61=window.__v5WaterfallBufferM61,md=window.__v5MicroDropsM59;let lines=[`XPBD ${x?.online?'ON':'fallback'} · ${x?.lastIterations??0} iter`,`RIGID HYDRO ${h?.online?'ON':'fallback'}`,`ADAPTIVE DETAIL ${a?.online?'ON':'fallback'} · ${a?.capacity||'--'}`,`WHITEWATER ${w?.online?'FINE':'fallback'}`,`MICRODROPS ${md?.online?'ON':'fallback'}`,`VOLUME LIGHT ${v?.online?'ON':'fallback'}`,`RAIN ${rain?.rainVisual?'ON':'fallback'} · STORM RIPPLES ${rain?.rippleVisual?'ON':'fallback'}`,`GLOBAL RIPPLES ${rp?.visual?'ON':'fallback'} · ${rp?.slots||'--'} slots`,`WATERFALL ${wf?.online?'PBF':'fallback'} · HOUDINI ${m60?.online?'ON':'fallback'} · BUFFER ${b61?.online?'M6.1 ON':'fallback'} · bucket ${b61?.bucket??'--'}/${b61?.buckets??'--'} · pumps ${b61?.pumps??0}`];d.lastElementChild.textContent=lines.join(' · ');}setInterval(tick,420);tick();
console.info('[Fluid V5 M6.1] controls and deterministic waterfall diagnostics mounted.');
