// Fluid V5 M6.2 integrated controls/status. Appends to the already-mounted tab shell.
const state=window.__v5State;if(!state)throw new Error('Fluid V5 M6.2 UI: state unavailable.');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));for(let i=0;i<40&&!document.querySelector('[data-panel="physics"]');i++)await sleep(50);
const physics=document.querySelector('[data-panel="physics"]'),realism=document.querySelector('[data-panel="realism"]'),dev=document.querySelector('[data-panel="developer"]');
const save=()=>{try{localStorage.setItem('fluidV5LabStateV1',JSON.stringify(state))}catch{}};
function section(host,id,title,desc){if(!host||document.getElementById(id))return null;let d=document.createElement('div');d.id=id;d.style.cssText='margin-top:10px;padding:9px;border:1px solid rgba(78,214,220,.18);border-radius:10px;background:rgba(4,17,24,.58)';d.innerHTML=`<div style="font:800 9px ui-monospace;color:#9dffc8;letter-spacing:.10em">${title}</div><div style="font:7.4px/1.45 ui-monospace;color:#86a8b5;margin-top:5px">${desc}</div>`;host.appendChild(d);return d;}
function slider(host,label,key,min,max,step,fmt=v=>Number(v).toFixed(2)){if(!host)return;let row=document.createElement('div');row.className='v5Slider';row.innerHTML=`<label>${label}</label><input type="range" min="${min}" max="${max}" step="${step}"><div class="v5Val"></div>`;let input=row.querySelector('input'),val=row.querySelector('.v5Val');input.value=state[key];let sync=()=>val.textContent=fmt(state[key]);sync();input.oninput=e=>{e.stopPropagation();state[key]=Number(input.value);save();sync()};host.appendChild(row);}
let p=section(physics,'v5M5Physics','M5 SOLVER REFINEMENT','XPBD-style compliant density refinement runs after the base PBF solve. Shape-aware hydrodynamics samples the same GPU neighbor grid on both fluid and rigid particles.');
slider(p,'XPBD DENSITY','xpbdDensity',0,1,.05);slider(p,'SHAPE HYDRO','shapeHydro',0,1.25,.05);
let r=section(realism,'v5M5Detail','M6.2 ADAPTIVE DETAIL','Sparse airborne splash parcels use microdroplet surfacing. The waterfall now uses a closed-loop submerged reservoir intake feeding real PBF fluid into the Houdini-style reconstructed body; no airborne parcel is time-recycled.');
slider(r,'SURFACE DETAIL','surfaceDetail',0,1.25,.05);
let d=section(dev,'v5M5Status','M6.2 BACKENDS','Waiting for subsystem status…');
function tick(){if(!d)return;let x=window.__v5XPBDM50,h=window.__v5RigidHydroM51,a=window.__v5AdaptiveDetailM52,v=window.__v5VolumeLightM53,w=window.__v5WhitewaterM54||window.__v5WhitewaterM41,rain=window.__v5WeatherM56,rp=window.__v5RippleM57,pump=window.__v5WaterfallM62,render=window.__v5WaterfallM60,md=window.__v5MicroDropsM59;let lines=[`XPBD ${x?.online?'ON':'fallback'} · ${x?.lastIterations??0} iter`,`RIGID HYDRO ${h?.online?'ON':'fallback'}`,`ADAPTIVE DETAIL ${a?.online?'ON':'fallback'} · ${a?.capacity||'--'}`,`WHITEWATER ${w?.online?'FINE':'fallback'}`,`MICRODROPS ${md?.online?'ON':'fallback'}`,`VOLUME LIGHT ${v?.online?'ON':'fallback'}`,`RAIN ${rain?.rainVisual?'ON':'fallback'} · STORM RIPPLES ${rain?.rippleVisual?'ON':'fallback'}`,`GLOBAL RIPPLES ${rp?.visual?'ON':'fallback'} · ${rp?.slots||'--'} slots`,`WATERFALL ${pump?.online?'RESERVOIR M6.2':'fallback'} · inlet ${pump?.across||'--'}×${pump?.thickness||'--'} · ${pump?.maxSpawn||0}/frame · HOUDINI ${render?.online?'ON':'fallback'}`];d.lastElementChild.textContent=lines.join(' · ');}setInterval(tick,420);tick();
console.info('[Fluid V5 M6.2] controls and reservoir-waterfall diagnostics mounted.');
