// Fluid V5 M5 integrated controls/status. Appends to the already-mounted M4.7 tab shell.
const state=window.__v5State;if(!state)throw new Error('Fluid V5 M5 UI: state unavailable.');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));for(let i=0;i<40&&!document.querySelector('[data-panel="physics"]');i++)await sleep(50);
const physics=document.querySelector('[data-panel="physics"]'),realism=document.querySelector('[data-panel="realism"]'),dev=document.querySelector('[data-panel="developer"]');
const save=()=>{try{localStorage.setItem('fluidV5LabStateV1',JSON.stringify(state))}catch{}};
function section(host,id,title,desc){if(!host||document.getElementById(id))return null;let d=document.createElement('div');d.id=id;d.style.cssText='margin-top:10px;padding:9px;border:1px solid rgba(78,214,220,.18);border-radius:10px;background:rgba(4,17,24,.58)';d.innerHTML=`<div style="font:800 9px ui-monospace;color:#9dffc8;letter-spacing:.10em">${title}</div><div style="font:7.4px/1.45 ui-monospace;color:#86a8b5;margin-top:5px">${desc}</div>`;host.appendChild(d);return d;}
function slider(host,label,key,min,max,step,fmt=v=>Number(v).toFixed(2)){if(!host)return;let row=document.createElement('div');row.className='v5Slider';row.innerHTML=`<label>${label}</label><input type="range" min="${min}" max="${max}" step="${step}"><div class="v5Val"></div>`;let input=row.querySelector('input'),val=row.querySelector('.v5Val');input.value=state[key];let sync=()=>val.textContent=fmt(state[key]);sync();input.oninput=e=>{e.stopPropagation();state[key]=Number(input.value);save();sync()};host.appendChild(row);}
let p=section(physics,'v5M5Physics','M5 SOLVER REFINEMENT','XPBD-style compliant density refinement runs after the base PBF solve. Shape-aware hydrodynamics samples the same GPU neighbor grid on both fluid and rigid particles, creating differential forces that become torque through the existing rigid shape matcher.');
slider(p,'XPBD DENSITY','xpbdDensity',0,1,.05);slider(p,'SHAPE HYDRO','shapeHydro',0,1.25,.05);
let r=section(realism,'v5M5Detail','M5 ADAPTIVE DETAIL','High-speed/high-curvature surface particles receive render-only refractive detail proxies. They add thin-sheet and splash-crown detail without changing fluid mass. Whitewater spray uses the M5.4 Fresnel/refractive shader.');
slider(r,'SURFACE DETAIL','surfaceDetail',0,1.25,.05);
let d=section(dev,'v5M5Status','M5 BACKENDS','Waiting for subsystem status…');
function tick(){if(!d)return;let x=window.__v5XPBDM50,h=window.__v5RigidHydroM51,a=window.__v5AdaptiveDetailM52,v=window.__v5VolumeLightM53,w=window.__v5WhitewaterM54||window.__v5WhitewaterM41,rain=window.__v5WeatherM56;let lines=[`XPBD ${x?.online?'ON':'fallback'} · ${x?.lastIterations??0} iter`,`RIGID HYDRO ${h?.online?'ON':'fallback'}`,`ADAPTIVE DETAIL ${a?.online?'ON':'fallback'} · ${a?.capacity||'--'}`,`WHITEWATER OPTICS ${w?.online?'ON':'fallback'}`,`VOLUME LIGHT ${v?.online?'ON':'fallback'}`,`WEATHER M5.6 ${rain?.online?'ON':'fallback'} · rain ${rain?.rainVisual||'--'} · sheet ${rain?.waterfallCells||'--'}`];d.lastElementChild.textContent=lines.join(' · ');}setInterval(tick,420);tick();
console.info('[Fluid V5 M5.6] controls and diagnostics mounted.');
